### ISSUE TITLE
grails 3 plugin upgrade

### ISSUE THREAD

**Issue by StevenACoffman** [j-a-w-r/jawr-grails#5]
Hello,
So grails 3 entails some changes to the plugins, but the easiest is that plugins are distributed as jars rather than zip files. Is there interest in upgrading this plugin to work with grails 3?

**Comment by ic3fox** [comment]
Hi,

This issue has been transfered to the main repo.
You'll be able to follow this issue [Here](https://github.com/j-a-w-r/jawr-main-repo/issues/39)
